### ISSUE TITLE
Missing callback to  acknowledge subscribe and unsubscribe

### ISSUE THREAD

**Issue by Beloa** [RangerMauve/mqtt-emitter#6]
Hi,

The current implementation does not allow to ack sub and unsub done in onAdd and onRemove
We should add a callback on addListner and removeListner and spread this callback to the onAdd and onRemove method.

Thanks

**Comment by RangerMauve** [comment]
Would you mind sketching out what your ideal API would look like?

This library doesn't integrate with MQTT clients directly, so you should be able to do something like this:

```javascript
emitter.onadd = function (topic) {
	mqtt.subscribe("topic", subackCallback);
}
emitter.onremove = function (topic) {
	mqtt.unsubscribe("topic", sunsubCallback);
}
```

I'd suggest creating a wrapper over the library if you need callbacks since everything within the library is already synchronous.

**Comment by Beloa** [comment]
Ok, thanks, I will do that
